# Dockerfile.dev
ARG ELIXIR_VERSION=1.18.4
ARG OTP_VERSION=27.3.4.1
ARG DEBIAN_VERSION=bullseye-20250630-slim

ARG BUILDER_IMAGE="hexpm/elixir:${ELIXIR_VERSION}-erlang-${OTP_VERSION}-debian-${DEBIAN_VERSION}"

FROM ${BUILDER_IMAGE}

# Install OS packages
RUN apt-get update -y && \
    apt-get install -y build-essential git npm inotify-tools

WORKDIR /app

# Install Hex & Rebar
RUN mix local.hex --force && mix local.rebar --force

# Copy and install Elixir deps
COPY mix.exs mix.lock ./
RUN mix deps.get

# Copy the rest of the code
COPY . .

# Install JS deps
RUN npm --prefix ./assets install

# Expose Phoenix server port
EXPOSE 4000

# Start Phoenix server
CMD ["mix", "phx.server"]
